services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
       - DATABASE_URL=postgresql://postgres:postgres@db:5432/test-db?schema=public
    environment:    
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/test-db?schema=public
    ports:
      - "3000:3000"
      - '5555:5555'
      
    volumes:
      - postgres-data:/var/lib/postgresql/data  
    depends_on:
     db:
        condition: service_healthy

  db:    
    image: postgres:alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test-db
      POSTGRES_MAX_CONNECTIONS: 200
    ports:
      - 5732:5432
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}' ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres-data:

